//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { Guid } from "@Obsidian/Types";

/**
 * A search result item that represents a single family member in check-in
 * family search.
 */
export type FamilyMemberSearchItemBag = {
    /**
     * Gets or sets the birth date. If this date is used, the time zone
     * information should be thrown away so that just the raw date is
     * left. Otherwise the birthdate might shift by one day depending
     * on the time zone.
     */
    birthDate?: string | null;

    /** Gets or sets the birth day. */
    birthDay?: number | null;

    /** Gets or sets the birth month. */
    birthMonth?: number | null;

    /** Gets or sets the birth year. */
    birthYear?: number | null;

    /** Gets or sets the person's gender. */
    gender: number;

    /** Gets or sets the unique identifier of the Person. */
    guid?: Guid | null;

    /** Gets or sets the last name. */
    lastName?: string | null;

    /** Gets or sets the person's nick name. */
    nickName?: string | null;

    /** Gets or sets the group role order. */
    roleOrder: number;
};
