//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { FamilyMemberBag } from "@Obsidian/ViewModels/CheckIn/familyMemberBag";
import { SelectedOptionsBag } from "@Obsidian/ViewModels/CheckIn/selectedOptionsBag";

/** A potential attendee item bag. */
export type PotentialAttendeeBag = {
    /** Gets or sets the message describing why this person is not available. */
    disabledMessage?: string | null;

    /** Gets or sets a value indicating whether this person is disabled. */
    isDisabled: boolean;

    /** Gets or sets a value indicating whether this instance is already selected. */
    isPreSelected: boolean;

    /** Gets or sets the person represented by this item. */
    person?: FamilyMemberBag | null;

    /** Gets or sets the selected options for this potential attendee. */
    selectedOptions?: SelectedOptionsBag | null;
};
